name: Publish Docker image
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]  
    
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com 
          
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build container image
        env:
          IMAGE_REPOSITORY: ${{github.IMAGE_REPOSITORY}}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{github.IMAGE_REPOSITORY}}/octo-image:${{ github.sha }}
            docker.pkg.github.com/${{github.IMAGE_REPOSITORY}}/octo-image:${{ github.ref }}
